"""empty message

Revision ID: 284034d542be
Revises: d93293a30436
Create Date: 2024-10-17 23:13:36.038748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284034d542be'
down_revision = 'd93293a30436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
