"""empty message

Revision ID: 5fc2966ced07
Revises: ca8c16b36f39
Create Date: 2024-11-05 11:08:54.696073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc2966ced07'
down_revision = 'ca8c16b36f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('type_threshold', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold')
    # ### end Alembic commands ###
