"""empty message

Revision ID: 7566c0302955
Revises: 5fc2966ced07
Create Date: 2024-11-05 22:00:08.861122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7566c0302955'
down_revision = '5fc2966ced07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test-record2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.Date(), nullable=False),
    sa.Column('knowledge', sa.String(length=100), nullable=False),
    sa.Column('questions', sa.String(), nullable=True),
    sa.Column('wrong_answer', sa.String(), nullable=True),
    sa.Column('result', sa.String(length=300), nullable=True),
    sa.Column('time_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test-record2')
    # ### end Alembic commands ###
