"""empty message

Revision ID: ca8c16b36f39
Revises: 284034d542be
Create Date: 2024-10-30 18:46:00.428441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8c16b36f39'
down_revision = '284034d542be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_types',
    sa.Column('id_subject', sa.String(length=10), nullable=False),
    sa.Column('chapter_num', sa.String(), nullable=False),
    sa.Column('problem_types', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('problem_types')
    )
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('problem_types')
    # ### end Alembic commands ###
