"""empty message

Revision ID: d93293a30436
Revises: 6e5dd40c8ccc
Create Date: 2024-10-04 11:53:37.646475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93293a30436'
down_revision = '6e5dd40c8ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_info',
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('chapter_num', sa.String(), nullable=False),
    sa.Column('lesson_num', sa.String(), nullable=False),
    sa.Column('lesson_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('subject', 'chapter_num', 'lesson_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_info')
    # ### end Alembic commands ###
