"""empty message

Revision ID: f58208af5bb4
Revises: 7566c0302955
Create Date: 2024-11-05 23:53:11.028380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58208af5bb4'
down_revision = '7566c0302955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question-answer2',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('options', sa.String(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.Column('explain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question-answer2')
    # ### end Alembic commands ###
